-- ============================================
-- XPLAY Data Migration: Manus DB → Vultr DB
-- Generated: 2026-03-16T11:52:25.078Z
-- ============================================

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- ===== faqItems (6 rows) =====
INSERT INTO faqItems (id, question, answer, sortOrder, isActive, createdAt, updatedAt) VALUES (1, '{"ko":"XPLAY는 안전한가요? 자금은 어떻게 보호되나요?","en":"Is XPLAY safe? How are funds protected?","zh":"XPLAY安全吗？资金如何保护？","ja":"XPLAYは安全ですか？資金はどう保護されますか？","vi":"XPLAY có an toàn không? Tiền được bảo vệ thế nào?","th":"XPLAY ปลอดภัยไหม? เงินถูกปกป้องอย่างไร?"}', '{"ko":"XPLAY는 Polygon 블록체인 기반 스마트 컨트랙트로 운영되며, 모든 거래가 온체인에 기록됩니다. 자금은 스마트 컨트랙트에 안전하게 보관되고, 출금은 사용자 본인만 가능합니다.","en":"XPLAY operates on Polygon blockchain smart contracts with all transactions recorded on-chain. Funds are securely held in smart contracts, and only users can withdraw their own funds.","zh":"XPLAY基于Polygon区块链智能合约运行，所有交易记录在链上。资金安全保管在智能合约中，只有用户本人可以提现。","ja":"XPLAYはPolygonブロックチェーンのスマートコントラクトで運営され、全取引がオンチェーンに記録されます。","vi":"XPLAY hoạt động trên smart contract Polygon blockchain, mọi giao dịch được ghi trên chain.","th":"XPLAY ทำงานบน smart contract Polygon blockchain ทุกธุรกรรมบันทึกบน chain"}', 0, 1, '2026-03-15 23:47:26', '2026-03-15 23:47:26') ON DUPLICATE KEY UPDATE question = VALUES(question), answer = VALUES(answer), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO faqItems (id, question, answer, sortOrder, isActive, createdAt, updatedAt) VALUES (2, '{"ko":"최소 투자 금액은 얼마인가요?","en":"What is the minimum investment amount?","zh":"最低投资金额是多少？","ja":"最低投資額はいくらですか？","vi":"Số tiền đầu tư tối thiểu là bao nhiêu?","th":"จำนวนเงินลงทุนขั้นต่ำเท่าไหร่?"}', '{"ko":"Sprint Bot 기준 최소 $100 USDT부터 시작할 수 있습니다. 봇별로 최소 금액이 다릅니다: Sprint($100), Velocity($300), Momentum($500), Quantum($1,000), Catalyst($2,000).","en":"You can start from $100 USDT with Sprint Bot. Minimum varies by bot: Sprint($100), Velocity($300), Momentum($500), Quantum($1,000), Catalyst($2,000).","zh":"Sprint Bot最低$100 USDT起。各机器人最低金额不同。","ja":"Sprint Botなら最低$100 USDTから。","vi":"Bắt đầu từ $100 USDT với Sprint Bot.","th":"เริ่มจาก $100 USDT กับ Sprint Bot"}', 1, 1, '2026-03-15 23:47:26', '2026-03-15 23:47:26') ON DUPLICATE KEY UPDATE question = VALUES(question), answer = VALUES(answer), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO faqItems (id, question, answer, sortOrder, isActive, createdAt, updatedAt) VALUES (3, '{"ko":"출금은 얼마나 걸리나요?","en":"How long does withdrawal take?","zh":"提现需要多长时间？","ja":"出金にはどのくらいかかりますか？","vi":"Rút tiền mất bao lâu?","th":"ถอนเงินใช้เวลานานเท่าไหร่?"}', '{"ko":"봇 수익율이 자동으로 6.25 USDT에 도달하면 20%를 제외하고 자동으로 지갑으로 입금됩니다. 자금은 모두 BNB체인 중심이지만 다양한 체인을 사용합니다.","en":"When bot earnings automatically reach 6.25 USDT, 20% is deducted and the remainder is automatically deposited to your wallet. Funds are primarily on BNB Chain but various chains are used.","zh":"当机器人收益自动达到6.25 USDT时，扣除20%后自动存入您的钱包。资金主要在BNB链上，但也使用多种链。","ja":"ボット収益が自動的に6.25 USDTに達すると、20%を差し引いて自動的にウォレットに入金されます。資金は主にBNBチェーンですが、様々なチェーンを使用しています。","vi":"Khi lợi nhuận bot tự động đạt 6.25 USDT, 20% được khấu trừ và phần còn lại tự động chuyển vào ví. Tiền chủ yếu trên BNB Chain nhưng sử dụng nhiều chain khác nhau.","th":"เมื่อรายได้บอทถึง 6.25 USDT อัตโนมัติ หัก 20% แล้วฝากเข้ากระเป๋าอัตโนมัติ เงินทุนส่วนใหญ่อยู่บน BNB Chain แต่ใช้หลาย chain"}', 2, 1, '2026-03-15 23:47:27', '2026-03-16 07:26:25') ON DUPLICATE KEY UPDATE question = VALUES(question), answer = VALUES(answer), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO faqItems (id, question, answer, sortOrder, isActive, createdAt, updatedAt) VALUES (4, '{"ko":"레퍼럴 보너스는 어떻게 작동하나요?","en":"How does the referral bonus work?","zh":"推荐奖金如何运作？","ja":"リファラルボーナスはどう機能しますか？","vi":"Thưởng giới thiệu hoạt động thế nào?","th":"โบนัสแนะนำทำงานอย่างไร?"}', '{"ko":"1세대 직접 추천 시 해당 투자금의 10%를 즉시 보너스로 받습니다. 2~6세대까지는 팀 배분 80%에서 단계별 보너스가 지급됩니다.","en":"You receive 10% instant bonus from 1st generation direct referrals. Generations 2-6 earn stepped bonuses from the 80% team distribution.","zh":"第1代直接推荐获得10%即时奖金。2-6代从80%团队分配中获得阶梯奖金。","ja":"1世代直接紹介で投資額の10%を即時ボーナス。2~6世代は80%チーム配分から段階的ボーナス。","vi":"Nhận 10% thưởng ngay từ giới thiệu trực tiếp thế hệ 1.","th":"รับโบนัสทันที 10% จากแนะนำตรงรุ่นที่ 1"}', 3, 1, '2026-03-15 23:47:27', '2026-03-15 23:47:27') ON DUPLICATE KEY UPDATE question = VALUES(question), answer = VALUES(answer), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO faqItems (id, question, answer, sortOrder, isActive, createdAt, updatedAt) VALUES (5, '{"ko":"BTC 예측 게임에서 잃으면 어떻게 되나요?","en":"What happens if I lose in the BTC prediction game?","zh":"BTC预测游戏输了怎么办？","ja":"BTC予測ゲームで負けたらどうなりますか？","vi":"Nếu thua trong game dự đoán BTC thì sao?","th":"ถ้าแพ้ในเกมทำนาย BTC จะเป็นอย่างไร?"}', '{"ko":"예측이 틀리면 해당 라운드의 베팅 금액을 잃게 됩니다. 하지만 수수료 5%를 제외한 풀의 95%가 승자에게 배분되므로 공정한 구조입니다. 소액($5)부터 시작하여 감을 익히는 것을 권장합니다.","en":"If your prediction is wrong, you lose the bet amount for that round. However, 95% of the pool (minus 5% fee) is distributed to winners, making it a fair structure.","zh":"预测错误会失去该回合的投注金额。但扣除5%手续费后95%分配给赢家，结构公平。","ja":"予測が外れるとそのラウンドの賭け金を失います。ただし手数料5%を除くプールの95%が勝者に配分される公正な構造。","vi":"Nếu dự đoán sai, bạn mất tiền đặt cược vòng đó. Nhưng 95% pool (trừ 5% phí) được chia cho người thắng.","th":"ถ้าทำนายผิด จะเสียเงินเดิมพันรอบนั้น แต่ 95% ของ pool (หัก 5% ค่าธรรมเนียม) แจกให้ผู้ชนะ"}', 4, 1, '2026-03-15 23:47:27', '2026-03-15 23:47:27') ON DUPLICATE KEY UPDATE question = VALUES(question), answer = VALUES(answer), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO faqItems (id, question, answer, sortOrder, isActive, createdAt, updatedAt) VALUES (6, '{"ko":"XPLAY를 시작하려면 어떤 지갑이 필요한가요?","en":"What wallet do I need to start with XPLAY?","zh":"开始使用XPLAY需要什么钱包？","ja":"XPLAYを始めるにはどのウォレットが必要ですか？","vi":"Cần ví gì để bắt đầu với XPLAY?","th":"ต้องใช้กระเป๋าอะไรเพื่อเริ่มใช้ XPLAY?"}', '{"ko":"TokenPocket 지갑을 권장합니다. dApp 브라우저가 내장되어 있어 XPLAY에 바로 접속할 수 있습니다. Polygon 네트워크를 지원하는 다른 지갑(MetaMask 등)도 사용 가능하지만, TokenPocket이 가장 편리합니다.","en":"We recommend TokenPocket wallet. It has a built-in dApp browser for direct XPLAY access. Other wallets supporting Polygon (like MetaMask) also work, but TokenPocket is the most convenient.","zh":"推荐TokenPocket钱包。内置dApp浏览器可直接访问XPLAY。","ja":"TokenPocketウォレットを推奨。dAppブラウザ内蔵でXPLAYに直接アクセス可能。","vi":"Khuyến nghị ví TokenPocket. Có trình duyệt dApp tích hợp để truy cập XPLAY trực tiếp.","th":"แนะนำกระเป๋า TokenPocket มีเบราว์เซอร์ dApp ในตัวเข้า XPLAY ได้โดยตรง"}', 5, 1, '2026-03-15 23:47:27', '2026-03-15 23:47:27') ON DUPLICATE KEY UPDATE question = VALUES(question), answer = VALUES(answer), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);

-- ===== tutorials (1 rows) =====
INSERT INTO tutorials (id, youtubeId, videoUrl, iconName, iconColor, title, description, tooltip, category, steps, sortOrder, isActive, createdAt, updatedAt) VALUES (1, 'none', 'https://d2xsxph8kpxj0f.cloudfront.net/310519663373200888/45mU6xhgdRUAikfBjGs2KY/xplay-staking_6e02c791.mp4', 'Wallet', '#a855f7', '{"ko":"XPLAY 스테이킹 완전 가이드","en":"XPLAY Staking Complete Guide","zh":"XPLAY质押完整指南","ja":"XPLAYステーキング完全ガイド","vi":"Hướng dẫn Staking XPLAY đầy đủ","th":"คู่มือ Staking XPLAY ฉบับสมบูรณ์"}', '{"ko":"XPLAY 스테이킹 방법을 영상으로 쉽게 배워보세요. 지갑 연결부터 수익 확인까지 단계별 안내","en":"Learn XPLAY staking easily with this video guide. Step-by-step from wallet connection to earnings check","zh":"通过视频轻松学习XPLAY质押。从钱包连接到收益查看的逐步指南","ja":"動画でXPLAYステーキングを簡単に学びましょう。ウォレット接続から収益確認まで","vi":"Học staking XPLAY dễ dàng qua video. Hướng dẫn từng bước từ kết nối ví đến kiểm tra lợi nhuận","th":"เรียนรู้การ Staking XPLAY ง่ายๆ ผ่านวิดีโอ ตั้งแต่เชื่อมต่อกระเป๋าถึงตรวจสอบรายได้"}', '{"ko":"영상으로 따라하면 3분이면 스테이킹 시작!","en":"Follow the video and start staking in 3 minutes!","zh":"跟着视频3分钟开始质押！","ja":"動画に沿って3分でステーキング開始！","vi":"Theo video và bắt đầu staking trong 3 phút!","th":"ทำตามวิดีโอเริ่ม Staking ใน 3 นาที!"}', 'beginner', '[{"title":{"ko":"1. 지갑 연결","en":"1. Connect Wallet"},"desc":{"ko":"TokenPocket 또는 MetaMask에서 Polygon 네트워크를 선택하고 XPLAY에 접속합니다.","en":"Select Polygon network in TokenPocket or MetaMask and connect to XPLAY."}},{"title":{"ko":"2. 봇 선택 & 금액 설정","en":"2. Select Bot & Set Amount"},"desc":{"ko":"Sprint, Velocity, Momentum 등 원하는 봇을 선택하고 투자 금액을 입력합니다.","en":"Choose your preferred bot (Sprint, Velocity, Momentum, etc.) and enter investment amount."}},{"title":{"ko":"3. 스테이킹 시작","en":"3. Start Staking"},"desc":{"ko":"트랜잭션을 승인하면 자동으로 스테이킹이 시작됩니다. 수익은 대시보드에서 실시간 확인 가능합니다.","en":"Approve the transaction and staking starts automatically. Check earnings in real-time on the dashboard."}}]', 0, 1, '2026-03-15 23:47:25', '2026-03-15 23:47:25') ON DUPLICATE KEY UPDATE youtubeId = VALUES(youtubeId), videoUrl = VALUES(videoUrl), iconName = VALUES(iconName), iconColor = VALUES(iconColor), title = VALUES(title), description = VALUES(description), tooltip = VALUES(tooltip), category = VALUES(category), steps = VALUES(steps), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);

-- ===== resources (10 rows) =====
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (1, 'document', 'ko', 'XPLAY 수익 구조 완전 분석 (PDF)', 'XPLAY의 AI 자동 수익 엔진과 GameFi 듀얼 엔진 수익 구조를 상세히 분석한 문서입니다.', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pdf', NULL, NULL, 1, 1, '2026-03-15 11:40:08', '2026-03-16 15:44:25') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (2, 'document', 'ko', 'XPLAY 프레젠테이션 (PPTX)', 'XPLAY 수익 구조와 비즈니스 모델을 시각적으로 설명한 프레젠테이션 자료입니다.', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pptx', NULL, NULL, 2, 1, '2026-03-15 11:42:02', '2026-03-15 11:42:02') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (3, 'document', 'en', 'XPLAY Revenue Structure (PDF)', 'Complete analysis of XPLAY\'s AI automated revenue engine and GameFi dual engine revenue structure.', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pdf', NULL, NULL, 3, 1, '2026-03-15 11:43:00', '2026-03-15 11:43:00') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (4, 'document', 'en', 'XPLAY Presentation (PPTX)', 'Visual presentation of XPLAY revenue structure and business model.', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pptx', NULL, NULL, 4, 1, '2026-03-15 11:43:01', '2026-03-15 11:43:01') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (5, 'document', 'zh', 'XPLAY 收益结构完全解析 (PDF)', 'XPLAY AI自动收益引擎和GameFi双引擎收益结构的详细分析文档。', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pdf', NULL, NULL, 5, 1, '2026-03-15 11:43:02', '2026-03-15 11:43:02') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (6, 'document', 'zh', 'XPLAY 双引擎 (PDF)', 'XPLAY双引擎系统详细技术文档。', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pdf', NULL, NULL, 6, 1, '2026-03-15 11:43:03', '2026-03-15 11:43:03') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (7, 'document', 'zh', 'XPLAY 演示文稿 (PPTX)', 'XPLAY收益结构和商业模式的视觉演示文稿。', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pptx', NULL, NULL, 7, 1, '2026-03-15 11:43:04', '2026-03-15 11:43:04') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (8, 'document', 'ja', 'XPLAY プレゼンテーション (PPTX)', 'XPLAYの収益構造とビジネスモデルを視覚的に説明したプレゼンテーション資料です。', NULL, 'https://frill-tuck-900.notion.site/X-PLAY-31f95eaa77f680d885a3c215497e3dc5', 'pptx', NULL, NULL, 8, 1, '2026-03-15 11:43:05', '2026-03-15 11:43:05') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (9, 'blog', 'ko', 'XPLAY 수익 구조 완전 분석', 'XPLAY의 AI 자동 수익 엔진과 GameFi 듀얼 엔진의 수익 구조를 상세히 분석한 블로그 포스트입니다.', 'https://blogthumb.pstatic.net/MjAyNjAzMTNfMTA2/MDAxNzczMzc4MjIzMTU1.Tig91Ik_eUyn73FpbM7QDFL0KGub6hvMdEK5WA-PTV4g.VclrdHVniS9f6qI8hfxO6ZQ-R1yvWG3Dzq-nkpL2fJAg.PNG/xplay_blog_thumbnail.png?type=w2', 'https://m.blog.naver.com/brodao/224215133571', NULL, 'Naver Blog', NULL, 9, 1, '2026-03-15 11:43:06', '2026-03-15 22:54:04') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);
INSERT INTO resources (id, type, lang, title, description, thumbnailUrl, url, fileType, platform, youtubeId, sortOrder, isActive, createdAt, updatedAt) VALUES (10, 'video', 'all', 'X Play Movie 소개영상', 'XPLAY 플랫폼의 수익 구조와 비즈니스 모델을 영상으로 소개합니다.', NULL, 'https://www.youtube.com/watch?v=fzsxiru7hAw', NULL, NULL, 'fzsxiru7hAw', 10, 1, '2026-03-15 11:43:07', '2026-03-15 11:43:07') ON DUPLICATE KEY UPDATE type = VALUES(type), lang = VALUES(lang), title = VALUES(title), description = VALUES(description), thumbnailUrl = VALUES(thumbnailUrl), url = VALUES(url), fileType = VALUES(fileType), platform = VALUES(platform), youtubeId = VALUES(youtubeId), sortOrder = VALUES(sortOrder), isActive = VALUES(isActive), updatedAt = VALUES(updatedAt);

-- ===== announcements (1 rows) =====
INSERT INTO announcements (id, title, content, imageUrl, isPinned, authorName, likeCount, status, scheduledAt, createdAt, updatedAt) VALUES (1, '공지사항 test', '공지사항 test', NULL, 0, 'XPLAY Admin', 0, 'published', NULL, '2026-03-15 14:03:43', '2026-03-15 14:03:43') ON DUPLICATE KEY UPDATE title = VALUES(title), content = VALUES(content), imageUrl = VALUES(imageUrl), isPinned = VALUES(isPinned), authorName = VALUES(authorName), status = VALUES(status), scheduledAt = VALUES(scheduledAt), updatedAt = VALUES(updatedAt);

-- newsLinks: No data

-- ===== urgentNotices (77 rows) =====
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (1, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 08:56:30', '2026-03-15 08:56:34') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (2, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-15 08:56:30', '2026-03-15 08:56:34') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (3, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-15 08:56:31', '2026-03-15 08:56:34') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (4, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 08:56:31', '2026-03-15 08:56:34') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (5, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-15 08:56:32', '2026-03-15 08:56:34') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (6, '활성 테스트 공지 1773550592676', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 08:56:32', '2026-03-15 08:56:34') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (7, '비활성화 테스트 1773550593347', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 08:56:33', '2026-03-15 08:56:33') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (9, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:32:34', '2026-03-15 10:32:38') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (10, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-15 10:32:35', '2026-03-15 10:32:38') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (11, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-15 10:32:35', '2026-03-15 10:32:38') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (12, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:32:36', '2026-03-15 10:32:38') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (13, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-15 10:32:36', '2026-03-15 10:32:38') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (14, '활성 테스트 공지 1773556356992', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:32:37', '2026-03-15 10:32:38') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (15, '비활성화 테스트 1773556357681', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:32:37', '2026-03-15 10:32:38') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (17, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:40', '2026-03-15 10:57:44') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (18, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-15 10:57:40', '2026-03-15 10:57:44') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (19, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-15 10:57:41', '2026-03-15 10:57:44') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (20, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:41', '2026-03-15 10:57:44') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (21, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:42', '2026-03-15 10:57:44') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (22, '활성 테스트 공지 1773557862520', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:42', '2026-03-15 10:57:44') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (23, '비활성화 테스트 1773557863226', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:43', '2026-03-15 10:57:43') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (25, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:56', '2026-03-15 10:58:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (26, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-15 10:57:57', '2026-03-15 10:58:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (27, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-15 10:57:57', '2026-03-15 10:58:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (28, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:58', '2026-03-15 10:58:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (29, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:58', '2026-03-15 10:58:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30, '활성 테스트 공지 1773557878855', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:58', '2026-03-15 10:58:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (31, '비활성화 테스트 1773557879567', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 10:57:59', '2026-03-15 10:58:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (33, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 11:16:39', '2026-03-15 11:16:43') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (34, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-15 11:16:40', '2026-03-15 11:16:43') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (35, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-15 11:16:40', '2026-03-15 11:16:43') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (36, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 11:16:40', '2026-03-15 11:16:43') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (37, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-15 11:16:41', '2026-03-15 11:16:43') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (38, '활성 테스트 공지 1773559001748', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 11:16:41', '2026-03-15 11:16:43') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (39, '비활성화 테스트 1773559002396', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 11:16:42', '2026-03-15 11:16:42') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (41, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 12:19:19', '2026-03-15 12:19:23') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (42, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-15 12:19:19', '2026-03-15 12:19:23') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (43, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-15 12:19:20', '2026-03-15 12:19:23') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (44, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 12:19:20', '2026-03-15 12:19:23') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (45, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-15 12:19:21', '2026-03-15 12:19:23') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (46, '활성 테스트 공지 1773562761500', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 12:19:21', '2026-03-15 12:19:23') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (47, '비활성화 테스트 1773562762178', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-15 12:19:22', '2026-03-15 12:19:22') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30001, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:32:57', '2026-03-16 07:33:01') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30002, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-16 07:32:57', '2026-03-16 07:33:01') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30003, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-16 07:32:58', '2026-03-16 07:33:01') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30004, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:32:58', '2026-03-16 07:33:01') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30005, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-16 07:32:59', '2026-03-16 07:33:01') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30006, '활성 테스트 공지 1773631979473', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:32:59', '2026-03-16 07:33:01') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30007, '비활성화 테스트 1773631980178', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:33:00', '2026-03-16 07:33:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30009, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:33:51', '2026-03-16 07:33:55') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30010, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-16 07:33:51', '2026-03-16 07:33:55') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30011, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-16 07:33:52', '2026-03-16 07:33:55') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30012, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:33:52', '2026-03-16 07:33:55') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30013, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-16 07:33:53', '2026-03-16 07:33:55') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30014, '활성 테스트 공지 1773632033434', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:33:53', '2026-03-16 07:33:55') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30015, '비활성화 테스트 1773632034123', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:33:54', '2026-03-16 07:33:54') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30017, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:58:12', '2026-03-16 07:58:16') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30018, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-16 07:58:12', '2026-03-16 07:58:16') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30019, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-16 07:58:13', '2026-03-16 07:58:16') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30020, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:58:13', '2026-03-16 07:58:16') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30021, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-16 07:58:14', '2026-03-16 07:58:16') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30022, '활성 테스트 공지 1773633494684', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:58:14', '2026-03-16 07:58:16') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30023, '비활성화 테스트 1773633495351', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 07:58:15', '2026-03-16 07:58:15') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30025, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:14:52', '2026-03-16 14:15:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30026, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-16 14:14:53', '2026-03-16 14:15:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30027, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-16 14:14:54', '2026-03-16 14:15:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30028, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:14:55', '2026-03-16 14:15:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30029, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-16 14:14:56', '2026-03-16 14:15:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30030, '활성 테스트 공지 1773656096940', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:14:57', '2026-03-16 14:15:00') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30031, '비활성화 테스트 1773656098282', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:14:58', '2026-03-16 14:14:59') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30033, '테스트 긴급 공지입니다.', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:49:03', '2026-03-16 14:49:11') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30034, '오늘 저녁 8시 Zoom 회의', 'zoom', 'https://zoom.us/j/123456789', '2026-03-15 20:00 KST', 0, 'XPLAY Admin', '2026-03-16 14:49:04', '2026-03-16 14:49:11') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30035, '텐센트 회의 안내', 'tencent', 'https://meeting.tencent.com/dm/xxx', '2026-03-16 14:00 KST', 0, 'XPLAY Admin', '2026-03-16 14:49:05', '2026-03-16 14:49:11') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30036, 'DeBox 회의 안내', 'debox', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:49:06', '2026-03-16 14:49:11') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30037, '구글 미팅 안내', 'google', 'https://meet.google.com/abc-defg-hij', NULL, 0, 'XPLAY Admin', '2026-03-16 14:49:07', '2026-03-16 14:49:11') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30038, '활성 테스트 공지 1773658147695', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:49:08', '2026-03-16 14:49:11') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);
INSERT INTO urgentNotices (id, message, meetingType, meetingLink, meetingTime, isActive, authorName, createdAt, updatedAt) VALUES (30039, '비활성화 테스트 1773658149096', 'general', NULL, NULL, 0, 'XPLAY Admin', '2026-03-16 14:49:09', '2026-03-16 14:49:10') ON DUPLICATE KEY UPDATE message = VALUES(message), meetingType = VALUES(meetingType), meetingLink = VALUES(meetingLink), meetingTime = VALUES(meetingTime), isActive = VALUES(isActive), authorName = VALUES(authorName), updatedAt = VALUES(updatedAt);

-- liveFeedConfig: No data

-- Total: 95 rows exported
